[tool.black]
line-length = 100
include = '\.py$'
exclude = '''
/(
     \.git
   | dist
   | tools/\.python
   | build
   | tools/\deps
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
   ".git/*",
   "dist/*",
   "tools/.python/*",
   "tools/deps/*",
   "build/*",
]
